import pandas as pd
import plotly.express as px
import gsheets
import json

# README: This file is for visualizing the color ratings data in 3D RGB space.
# It reads from a local CSV file (which should be generated by recsys.py after pulling data from Google Sheets)
# and creates a 3D scatter plot where each point represents a color, positioned according to its RGB values and
# sized according to the average rating it received.

def main():
    # Pull data from Google Sheets and save to local CSV file
    gsheets.gsheets_pull()
    # Load CSV file into a DataFrame, with no header row because responses.csv contains only rating values
    df = pd.read_csv("responses.csv", header=None)
    if df.empty:
        print("No data available to visualize.")
        return
    # Sample data: ([r,g,b], color_idx, rating)
    avg_ratings = average_ratings(df)
    rating_count = count_ratings(df)
    # For visualization, we need to map color_idx back to RGB values.
    with open("colors_data.json", "r") as f:
        colors_data = json.load(f)
    ids = colors_data['id_cells']
    colors = colors_data['color_cells']
    # data format should be: ([r,g,b], color_idx, rating)
    avgs_data = parse_rgb(colors, ids, avg_ratings)
    count_data = parse_rgb(colors, ids, rating_count)
    # plot the colors in 3D RGB space, with size based on average rating
    plot_avg_color_ratings(avgs_data)
    plot_avg_color_ratings_inverse(avgs_data)
    # plot the number of ratings per color as a scatter plot in RGB space, with size based on count of ratings
    plot_rating_counts(count_data)
    return


# REQUIRES: colors (list of color strings like '[r,g,b]'), 
#   ids (list of color IDs), avg_ratings (DataFrame with ColorIdx and Rating columns)
# MODIFIES: None
# EFFECTS: Returns a list of tuples in the format ([r,g,b], color_idx, rating) for each color
def parse_rgb(colors, ids, avg_ratings):
    id_to_color = {int(id_value): color for id_value, color in zip(ids, colors)}
    data = []
    for idx, avg_rating in zip(avg_ratings['ColorIdx'], avg_ratings['Rating']):
        idx = int(idx)
        color_str = id_to_color[idx]
        rgb = color_str.strip("[]").split(",")
        r, g, b = int(rgb[0]), int(rgb[1]), int(rgb[2])
        data.append(([r, g, b], idx, avg_rating))
    return data

# REQUIRES: DataFrame with user ratings for each color (columns are color IDs, rows are user ratings)
# MODIFIES: None
# EFFECTS: Returns a DataFrame with average rating for each color ID
def average_ratings(df):
    # Each column in the CSV corresponds to a color ID, each row a user's rating for that color
    # Treat 0 as missing / no rating, so only ratings > 0 contribute to the mean
    rating_avg = df.where(df > 0).mean(axis=0)  # Average rating for each color ID, ignoring zeros
    rating_avg = rating_avg.reset_index()  # Convert Series to DataFrame
    rating_avg.columns = ['ColorIdx', 'Rating']  # Rename columns for clarity
    return rating_avg

def count_ratings(df):
    # Count the number of ratings (non-zero entries) for each color ID
    rating_count = df.where(df > 0).count(axis=0)  # Count of ratings for each color ID, ignoring zeros
    rating_count = rating_count.reset_index()  # Convert Series to DataFrame
    rating_count.columns = ['ColorIdx', 'Rating']  # Rename columns for compatibility with parse_rgb
    return rating_count


# REQUIRES: data in the format ([r,g,b], color_idx, rating)
# MODIFIES: None
# EFFECTS: Creates a 3D scatter plot of colors in RGB space, with point size based on rating
def plot_avg_color_ratings(data):
    rows = []
    for (r, g, b), idx, rating in data:
        rows.append({
            'r': r,
            'g': g,
            'b': b,
            'color_id': idx,
            'avg_rating': rating,
            'rgb': f"{r},{g},{b}",
            'size': rating ** 10,
            'hover_name': f"Color {idx}",
        })

    plot_df = pd.DataFrame(rows)
    fig = px.scatter_3d(
        plot_df,
        x='r',
        y='g',
        z='b',
        size='size',
        size_max=50,
        hover_name='hover_name',
        custom_data=['avg_rating', 'rgb'],
    )
    fig.update_traces(
        marker=dict(color=[f'rgb({r},{g},{b})' for r, g, b in zip(plot_df['r'], plot_df['g'], plot_df['b'])], opacity=0.8),
        hovertemplate='Color ID: %{hovertext}<br>Average rating: %{customdata[0]:.2f}<br>RGB: %{customdata[1]}<extra></extra>',
    )
    fig.update_layout(
        scene=dict(
            xaxis_title='Red',
            yaxis_title='Green',
            zaxis_title='Blue',
            xaxis=dict(range=[0, 255]),
            yaxis=dict(range=[0, 255]),
            zaxis=dict(range=[0, 255])
        )
    )
    fig.show()

# REQUIRES: data in the format ([r,g,b], color_idx, rating)
# MODIFIES: None
# EFFECTS: Creates a 3D scatter plot of colors in RGB space, with point size based on rating
def plot_avg_color_ratings_inverse(data):
    rows = []
    for (r, g, b), idx, rating in data:
        rows.append({
            'r': r,
            'g': g,
            'b': b,
            'color_id': idx,
            'avg_rating': rating,
            'rgb': f"{r},{g},{b}",
            'size': rating ** -10,
            'hover_name': f"Color {idx}",
        })

    plot_df = pd.DataFrame(rows)
    fig = px.scatter_3d(
        plot_df,
        x='r',
        y='g',
        z='b',
        size='size',
        size_max=50,
        hover_name='hover_name',
        custom_data=['avg_rating', 'rgb'],
    )
    fig.update_traces(
        marker=dict(color=[f'rgb({r},{g},{b})' for r, g, b in zip(plot_df['r'], plot_df['g'], plot_df['b'])], opacity=0.8),
        hovertemplate='Color ID: %{hovertext}<br>Average rating: %{customdata[0]:.2f}<br>RGB: %{customdata[1]}<extra></extra>',
    )
    fig.update_layout(
        scene=dict(
            xaxis_title='Red',
            yaxis_title='Green',
            zaxis_title='Blue',
            xaxis=dict(range=[0, 255]),
            yaxis=dict(range=[0, 255]),
            zaxis=dict(range=[0, 255])
        )
    )
    fig.show()

def plot_rating_counts(data):
    rows = []
    for (r, g, b), idx, rating in data:
        rows.append({
            'r': r,
            'g': g,
            'b': b,
            'color_id': idx,
            'rating_count': rating,
            'rgb': f"{r},{g},{b}",
            'size': rating**10,
            'hover_name': f"Color {idx}",
        })

    plot_df = pd.DataFrame(rows)
    fig = px.scatter_3d(
        plot_df,
        x='r',
        y='g',
        z='b',
        size='size',
        size_max=50,
        hover_name='hover_name',
        custom_data=['rating_count', 'rgb'],
    )
    fig.update_traces(
        marker=dict(color=[f'rgb({r},{g},{b})' for r, g, b in zip(plot_df['r'], plot_df['g'], plot_df['b'])], opacity=0.8),
        hovertemplate='Color ID: %{hovertext}<br>Rating count: %{customdata[0]:.0f}<br>RGB: %{customdata[1]}<extra></extra>',
    )
    fig.update_layout(
        scene=dict(
            xaxis_title='Red',
            yaxis_title='Green',
            zaxis_title='Blue',
            xaxis=dict(range=[0, 255]),
            yaxis=dict(range=[0, 255]),
            zaxis=dict(range=[0, 255])
        )
    )
    fig.show()

if __name__ == "__main__":
    main()